spring:
  application:
    name: cima-alm
  datasource:
    url: jdbc:postgresql://localhost:5432/cima_alm
    username: postgres
    password: root
  sql:
    init:
      mode: always
      data-locations: classpath:db/seed-data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
